"""add user_profiles table

Revision ID: 990b6d635503
Revises: a632f56a4935
Create Date: 2025-09-04 09:52:19.259481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '990b6d635503'
down_revision: Union[str, Sequence[str], None] = 'a632f56a4935'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profiles',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('mood', sa.Enum('NEUTRAL', 'HAPPY', 'SAD', 'ANGRY', 'CURIOUS', 'REFLECTIVE', name='usermood'), nullable=False),
    sa.Column('archetype', sa.Enum('EXPLORER', 'ACHIEVER', 'SOCIALIZER', 'PHILOSOPHER', 'CREATOR', name='userarchetype'), nullable=False),
    sa.Column('engagement_score', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_profiles')
    # ### end Alembic commands ###
